{
    'name': "Hospital Management System",
    'summary': "Test",
    'author': "My Company",
    'category': 'Uncategorized',
    'license': 'LGPL-3',
    'sequence': 1,
    'version': '17.0.1.0',
    'depends': ['mail', 'product', 'account'],
    'application': True,
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/patient_views.xml',
        'views/patient_tag_views.xml',
        'views/patient_readonly_views.xml',
        'views/appointment_views.xml',
        'views/appointment_line_views.xml',
        'views/account_move_views.xml',
        'views/menu.xml',
    ],
}
